security:
    # encoders:
    #    App\Entity\Student:
    #       algorithm: bcrypt
    #       cost: 12
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Student
                property: code
        app_person_in_charge_provider:
            entity:
                class: App\Entity\PersonInCharge
                property: code
        app_administrator_provider:
            entity:
                class: App\Entity\Administrator
                property: schoolCode
        app_hwi:
            id: App\Security\UserProvider

        # used to reload user from session & other features (e.g. switch_user)
        chain_provider:
            chain:
                providers: [app_user_provider, app_person_in_charge_provider, app_administrator_provider, app_hwi]


        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
#        secured_area:
#            anonymous: ~
#            oauth:
#                resource_owners:
#                    auth0: "/auth0/callback"
#                login_path:        /login
#                default_target_path: welcome
#                use_forward:       false
#                failure_path:      /login
#
#                provider: chain_provider
#
#                oauth_user_provider:
#                    service: App\Security\UserProvider
#
#            logout:
#                path:   /auth0/logout
#                target: welcome

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #main:
        secured_area:
            anonymous: true
            provider: chain_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path:   app_logout
                target: app_login

            oauth:
                resource_owners:
                    auth0: "/auth0/callback"
                login_path:        /login
                default_target_path: user_page
                use_forward:       false
                failure_path:      /login

                provider: chain_provider

                oauth_user_provider:
                    service: App\Security\UserProvider


            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/userpage, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }
